# Generated by Django 5.2.2 on 2025-06-14 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_key', models.CharField(db_index=True, help_text='Temp uuid', max_length=32, unique=True)),
                ('title', models.CharField(help_text='Menu title displayed in the admin.', max_length=50, verbose_name='Title')),
                ('url', models.CharField(blank=True, default='', help_text='URL or named route for the menu item.', max_length=200, verbose_name='URL')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon class for the menu item.', max_length=50, verbose_name='Icon')),
                ('app_label', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=10000, help_text='Order for menu sorting.', verbose_name='Sort Order')),
                ('permission', models.CharField(blank=True, default='', help_text='Permission code to control menu visibility.', max_length=100, verbose_name='Permission Code')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this menu is active and visible.', verbose_name='Active')),
                ('visible', models.BooleanField(default=True, help_text='Whether this menu is visible.', verbose_name='Visible')),
                ('remark', models.CharField(blank=True, default='', help_text='Additional notes or comments about this menu item.', max_length=200, verbose_name='Remark')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='Time when this menu item was last updated.', verbose_name='Update Time')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu for hierarchical structure.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cmfadmin.menu', verbose_name='Parent Menu')),
            ],
            options={
                'verbose_name': 'Admin Menu',
                'verbose_name_plural': 'Admin Menus',
                'ordering': ['sort_order'],
            },
        ),
    ]
