# Generated by Django 5.2.3 on 2025-06-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='update_time',
        ),
        migrations.AddField(
            model_name='menu',
            name='update_at',
            field=models.DateTimeField(auto_now=True, help_text='Time when this menu item was last updated.', verbose_name='Update At'),
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('site', 'Site Information'), ('seo', 'SEO Settings'), ('cdn', 'CDN Settings')], max_length=20, verbose_name='Category')),
                ('key', models.CharField(max_length=64, verbose_name='Key')),
                ('value', models.TextField(verbose_name='Value')),
                ('type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('image', 'Image'), ('switch', 'Switch'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('richtext', 'Rich Text'), ('password', 'Password'), ('number', 'Number'), ('file', 'File')], default='text', max_length=20, verbose_name='Type')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
            ],
            options={
                'verbose_name': 'Configuration Item',
                'verbose_name_plural': 'Configuration Items',
                'unique_together': {('category', 'key')},
            },
        ),
    ]
