# Generated by Django 6.0.2 on 2026-03-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0007_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
        migrations.DeleteModel(
            name='FileConfig',
        ),
        migrations.CreateModel(
            name='TestConfig',
            fields=[
            ],
            options={
                'verbose_name': 'test settings',
                'verbose_name_plural': 'test settings',
                'proxy': True,
                'default_permissions': ('view', 'change'),
                'indexes': [],
                'constraints': [],
            },
            bases=('cmfadmin.config',),
        ),
        migrations.AlterField(
            model_name='config',
            name='category',
            field=models.CharField(choices=[('site', 'Site Information'), ('email', 'Email Settings'), ('upload', 'Upload Settings'), ('file', 'File Management'), ('icons', 'Icons Management'), ('template', 'Template Management'), ('system', 'System Settings'), ('log', 'Log Management'), ('nav', 'Navigation Management'), ('links', 'External Links'), ('test', 'Test Management')], db_comment='Configuration category.', max_length=32, verbose_name='category'),
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
