# Generated by Django 6.0.3 on 2026-03-20 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0009_resource_delete_testconfig_alter_emailconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file_type',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video'), ('audio', 'audio'), ('document', 'document'), ('archive', 'archive')], default='', max_length=20, verbose_name='file type'),
        ),
        migrations.AddField(
            model_name='resource',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='MIME type'),
        ),
        migrations.AlterField(
            model_name='config',
            name='category',
            field=models.CharField(choices=[('site', 'Site Information'), ('email', 'Email Settings'), ('upload', 'Upload Settings'), ('file', 'File Management'), ('icons', 'Icons Management'), ('template', 'Template Management'), ('system', 'System Settings'), ('log', 'Log Management'), ('nav', 'Navigations'), ('links', 'External Links')], help_text='Configuration category.', max_length=32, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(help_text='Unique configuration key.', max_length=64, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='config',
            name='remark',
            field=models.CharField(blank=True, help_text='Additional notes about this configuration item.', max_length=255, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.TextField(help_text='Configuration value.', verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='app_label',
            field=models.CharField(blank=True, default='', help_text='Application label associated with this menu item.', max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Icon class for the menu item.', max_length=50, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_key',
            field=models.CharField(db_index=True, help_text='Stable hash used to uniquely identify this menu item, based on URL and parent id.', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent menu for hierarchical structure.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cmfadmin.menu', verbose_name='parent menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text='Permissions associated with this menu item.', max_length=255),
        ),
        migrations.AlterField(
            model_name='menu',
            name='remark',
            field=models.CharField(blank=True, default='', help_text='Additional notes or comments about this menu item.', max_length=200, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sort_order',
            field=models.PositiveIntegerField(default=10000, help_text='Order for menu sorting.', verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(help_text='Menu title displayed in the admin.', max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, default='', help_text='URL or named route for the menu item.', max_length=200, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='original_name',
            field=models.CharField(blank=True, default='', help_text='The original file name of the uploaded file', max_length=255, verbose_name='original name'),
        ),
    ]
