# Generated by Django 6.0.3 on 2026-04-12 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0013_urlalias_alter_nav_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('preview', models.CharField(blank=True, max_length=200)),
                ('directory', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'themes',
                'ordering': ['-installed_at'],
            },
        ),
        migrations.AlterField(
            model_name='urlalias',
            name='alias',
            field=models.CharField(help_text='The alias path without leading slash, e.g. news or about/team', max_length=255, unique=True, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='urlalias',
            name='target',
            field=models.CharField(help_text='The internal URL path this alias points to, must start with a leading slash and must be a valid registered URL, e.g. /content/category/abc123/', max_length=255, verbose_name='Target URL'),
        ),
        migrations.CreateModel(
            name='ThemeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('config', models.JSONField(default=dict)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='cmfadmin.theme')),
            ],
            options={
                'verbose_name': 'theme template',
                'verbose_name_plural': 'theme templates',
                'ordering': ['order'],
                'unique_together': {('theme', 'filename')},
            },
        ),
    ]
