# Generated by Django 6.0.3 on 2026-04-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0015_alter_themetemplate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='vars',
        ),
        migrations.RemoveField(
            model_name='themetemplate',
            name='vars',
        ),
    ]
