# Generated by Django 6.0.3 on 2026-04-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0016_remove_theme_vars_remove_themetemplate_vars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nav',
            options={'ordering': ['group', 'sort_order'], 'verbose_name': 'navigation', 'verbose_name_plural': 'navigations'},
        ),
        migrations.RemoveField(
            model_name='nav',
            name='nav_type',
        ),
        migrations.AddField(
            model_name='nav',
            name='group',
            field=models.CharField(default='main', help_text='Which navigation group this item belongs to.', max_length=100, verbose_name='group'),
            preserve_default=False,
        ),
    ]
