# Generated by Django 6.0.5 on 2026-05-14 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title for the external link.', max_length=50, verbose_name='title')),
                ('url', models.URLField(blank=True, help_text='The URL for the external link.', verbose_name='url')),
                ('image', models.ImageField(blank=True, help_text='The image associated with the external link.', null=True, upload_to='links/', verbose_name='image')),
                ('status', models.BooleanField(default=True, help_text='Indicates whether this link is active.', verbose_name='status')),
                ('sort_order', models.PositiveIntegerField(default=10000, help_text='Determines the display order of the link.', verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'Partner Link',
                'verbose_name_plural': 'Partner Links',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('subtitle', models.TextField(blank=True, verbose_name='subtitle')),
                ('image', models.ImageField(blank=True, upload_to='slider/', verbose_name='image')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='link')),
                ('group', models.CharField(max_length=100, verbose_name='group')),
                ('sort_order', models.IntegerField(default=10000, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'sliders',
                'ordering': ['group', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('preview', models.CharField(blank=True, max_length=200)),
                ('directory', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'themes',
                'ordering': ['-installed_at'],
            },
        ),
        migrations.CreateModel(
            name='UrlAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='The alias path without leading slash, e.g. news or about/team', max_length=255, unique=True, verbose_name='Alias')),
                ('target', models.CharField(help_text='The internal URL path this alias points to, must start with a leading slash and must be a valid registered URL, e.g. /content/category/abc123/', max_length=255, verbose_name='Target URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'URL Alias',
                'verbose_name_plural': 'URL Aliases',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('site', 'Site Information'), ('email', 'Email Settings'), ('upload', 'Upload Settings'), ('file', 'File Management'), ('icons', 'Icons Management'), ('template', 'Template Management'), ('system', 'System Settings'), ('log', 'Log Management'), ('nav', 'Navigations'), ('links', 'External Links')], help_text='Configuration category.', max_length=32, verbose_name='category')),
                ('key', models.CharField(help_text='Unique configuration key.', max_length=64, verbose_name='key')),
                ('value', models.TextField(help_text='Configuration value.', verbose_name='value')),
                ('remark', models.CharField(blank=True, help_text='Additional notes about this configuration item.', max_length=255, verbose_name='remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'configuration item',
                'verbose_name_plural': 'configuration items',
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('category', 'key'), name='unique_config_category_key')],
            },
        ),
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
            ],
            options={
                'verbose_name': 'Email Setting',
                'verbose_name_plural': 'Email Settings',
                'proxy': True,
                'default_permissions': ('view', 'change'),
                'indexes': [],
                'constraints': [],
            },
            bases=('padmin.config',),
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
            ],
            options={
                'verbose_name': 'Site Information',
                'verbose_name_plural': 'Site Information',
                'proxy': True,
                'default_permissions': ('view', 'change'),
                'indexes': [],
                'constraints': [],
            },
            bases=('padmin.config',),
        ),
        migrations.CreateModel(
            name='UploadConfig',
            fields=[
            ],
            options={
                'verbose_name': 'Upload Setting',
                'verbose_name_plural': 'Upload Settings',
                'proxy': True,
                'default_permissions': ('view', 'change'),
                'indexes': [],
                'constraints': [],
            },
            bases=('padmin.config',),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_key', models.CharField(db_index=True, help_text='Stable hash used to uniquely identify this menu item, based on URL and parent id.', max_length=32, unique=True)),
                ('title', models.CharField(help_text='Menu title displayed in the admin.', max_length=50, verbose_name='title')),
                ('url', models.CharField(blank=True, default='', help_text='URL or named route for the menu item.', max_length=200, verbose_name='url')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon class for the menu item.', max_length=50, verbose_name='icon')),
                ('app_label', models.CharField(blank=True, default='', help_text='Application label associated with this menu item.', max_length=50)),
                ('permissions', models.JSONField(blank=True, default=list, help_text='Permissions associated with this menu item.', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=10000, help_text='Order for menu sorting.', verbose_name='sort order')),
                ('remark', models.CharField(blank=True, default='', help_text='Additional notes or comments about this menu item.', max_length=200, verbose_name='remark')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu for hierarchical structure.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='padmin.menu', verbose_name='parent menu')),
            ],
            options={
                'verbose_name': 'admin menu',
                'verbose_name_plural': 'admin menus',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(help_text='Which navigation group this item belongs to.', max_length=100, verbose_name='group')),
                ('url', models.CharField(blank=True, default='', help_text='URL for this navigation item.', max_length=255, verbose_name='url')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon class for this navigation item.', max_length=100, verbose_name='icon class')),
                ('target', models.CharField(choices=[('_self', 'Self Window'), ('_blank', 'Blank Window')], default='_self', help_text='Target behavior when opening the link.', max_length=10, verbose_name='target')),
                ('sort_order', models.PositiveIntegerField(default=10000, help_text='Order for sorting.', verbose_name='sort order')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this item is visible.', verbose_name='is visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent item for hierarchical structure.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='padmin.nav', verbose_name='parent item')),
            ],
            options={
                'verbose_name': 'navigation',
                'verbose_name_plural': 'navigations',
                'ordering': ['group', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Relative path for local files, full URL for external resources.', max_length=2048, unique=True, verbose_name='URL')),
                ('original_name', models.CharField(blank=True, default='', help_text='The original file name of the uploaded file', max_length=255, verbose_name='original name')),
                ('size', models.PositiveIntegerField(default=0, help_text='File size in bytes. 0 for external resources.', verbose_name='size')),
                ('hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 hex digest. Empty for external resources.', max_length=64, verbose_name='hash')),
                ('file_type', models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video'), ('audio', 'audio'), ('document', 'document'), ('archive', 'archive')], default='', max_length=20, verbose_name='file type')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='MIME type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NavTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('zh-hans', '简体中文'), ('ja', '日本語'), ('ar', 'العربيّة')], db_index=True, default='zh-hans', help_text='Which language this translation belongs to.', max_length=10, verbose_name='language')),
                ('name', models.CharField(help_text='Display name of this navigation item.', max_length=100, verbose_name='name')),
                ('nav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='padmin.nav', verbose_name='navigation item')),
            ],
            options={
                'verbose_name': 'nav translation',
                'verbose_name_plural': 'nav translations',
                'unique_together': {('nav', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ThemeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=10000)),
                ('config', models.JSONField(default=dict)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='padmin.theme')),
            ],
            options={
                'verbose_name': 'theme template',
                'verbose_name_plural': 'theme templates',
                'ordering': ['sort_order'],
                'unique_together': {('theme', 'filename')},
            },
        ),
    ]
