# Generated by Django 6.0.5 on 2026-05-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='app_label',
            field=models.CharField(default='content', max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('app_label',), name='unique_active_theme_per_app'),
        ),
    ]
