# Generated by Django 6.0.5 on 2026-05-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padmin', '0002_theme_app_label_theme_unique_active_theme_per_app'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='themetemplate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='themetemplate',
            constraint=models.UniqueConstraint(fields=('theme', 'filename'), name='unique_theme_filename'),
        ),
    ]
