site_name: Pinmok Documentation
site_url: https://docs.pinmok.com/
docs_dir: docs
repo_url: https://github.com/pinmok/pinmok
repo_name: pinmok/pinmok

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        - locale: en
          name: English
          default: true
          build: true
          site_name: Pinmok Documentation
        - locale: zh
          name: 简体中文
          build: true
          site_name: Pinmok 文档
          nav_translations:
            Preface: 前言
            Getting Started: 快速开始
            Core Concepts: 核心概念
            Menu System: 菜单系统
            Model Registration: 模型注册
            Utilities: 工具集
            Theming: 主题
            Internationalization: 国际化
            Template Tags: 标签
            Appendix: 附录

nav:
  - Preface: index.md
  - Getting Started: getting-started.md
  - Core Concepts: concepts.md
  - Menu System: menus.md
  - Model Registration: models.md
  - Utilities: utils.md
  - Theming: theme.md
  - Internationalization: i18n.md
  - Template Tags: tags.md
  - Appendix: appendix.md