# Site information
site_name: Pinmok Documentation
site_url: https://docs.pinmok.com/
site_author: 惠达浪
docs_dir: docs

# Repository
repo_url: https://github.com/pinmok/pinmok
repo_name: pinmok/pinmok

# Copyright
copyright: Copyright &copy; 2025 - 2026 <a href="https://www.qdcrazy.cn" target="_blank">惠达浪</a> All right reserved.

# Configuration
theme:
  name: material
  custom_dir: overrides
  language: zh
  logo: assets/images/pinmok.bg.svg
  favicon: assets/images/favicon.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - content.code.copy
    - toc.follow
    - toc.integrate
    - search.highlight
  palette:
    primary: indigo

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

extra:
  generator: false

nav:
  - Preface: index.md
  - Getting Started: getting-started.md
  - Concepts: concepts.md
  - Menus: menus.md
  - Model Management: model-admin.md
  - Theme: theme.md
  - Template Tags: tags.md
  - Internationalization: i18n.md
  - Utilities: utils.md
  - Appendix: appendix.md

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          theme:
            palette:
              primary: blue
        - locale: zh
          name: 简体中文
          default: true
          site_name: Pinmok 开发文档
          nav_translations:
            Preface: 前言
            Getting Started: 入门指南
            Concepts: 核心概念
            Menus: 菜单
            Model Management: 模型管理
            Theme: 主题
            Template Tags: 模板标签
            Internationalization: 国际化
            Utilities: 实用工具
            Appendix: 附录