# Generated by Django 5.2.8 on 2025-11-23 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title for the external link.', max_length=50, verbose_name='Title')),
                ('url', models.URLField(blank=True, help_text='The URL for the external link.', verbose_name='URL')),
                ('image_url', models.CharField(blank=True, help_text='The image associated with the external link.', max_length=255, null=True, verbose_name='Image')),
                ('image', models.ImageField(blank=True, help_text='The image associated with the external link.', null=True, upload_to='links/', verbose_name='Image')),
                ('status', models.BooleanField(default=True, help_text='Indicates whether this link is active.', verbose_name='Status')),
                ('sort_order', models.IntegerField(default=10000, help_text='Determines the display order of the link.', verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'External Link',
                'verbose_name_plural': 'External Links',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codename', models.CharField(max_length=128, unique=True)),
                ('menu_key', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Menu Permission',
                'verbose_name_plural': 'Menu Permissions',
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title for the navigation.', max_length=100, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(help_text='A short unique identifier used in URLs and templates. Only letters, numbers, hyphens, and underscores are allowed.', max_length=100, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this navigation is active.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when this navigation was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when this navigation was last updated.', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Navigation',
                'verbose_name_plural': 'Navigations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('site', 'Site Information'), ('email', 'Email Settings'), ('email_template', 'Email Template'), ('links', 'External Links'), ('nav', 'Navigation Management'), ('template', 'Template Management'), ('system', 'System Settings'), ('upload', 'Upload Settings'), ('icons', 'Icons Management'), ('log', 'Log Management'), ('file', 'File Management')], help_text='Configuration category.', max_length=20, verbose_name='Category')),
                ('key', models.CharField(help_text='Unique configuration key.', max_length=64, verbose_name='Key')),
                ('value', models.TextField(help_text='Configuration value.', verbose_name='Value')),
                ('remark', models.CharField(blank=True, help_text='Additional notes about this configuration item.', max_length=255, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when this configuration was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when this configuration was last updated.', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Configuration Item',
                'verbose_name_plural': 'Configuration Items',
                'constraints': [models.UniqueConstraint(fields=('category', 'key'), name='unique_config_category_key')],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_key', models.CharField(db_index=True, help_text='Stable hash used to uniquely identify this menu item, based on URL and parent id.', max_length=32, unique=True)),
                ('title', models.CharField(help_text='Menu title displayed in the admin.', max_length=50, verbose_name='Title')),
                ('url', models.CharField(blank=True, default='', help_text='URL or named route for the menu item.', max_length=200, verbose_name='URL')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon class for the menu item.', max_length=50, verbose_name='Icon')),
                ('app_label', models.CharField(blank=True, default='', help_text='Application label associated with this menu item.', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=10000, help_text='Order for menu sorting.', verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this menu is active and visible.', verbose_name='Active')),
                ('visible', models.BooleanField(default=True, help_text='Whether this menu is visible.', verbose_name='Visible')),
                ('remark', models.CharField(blank=True, default='', help_text='Additional notes or comments about this menu item.', max_length=200, verbose_name='Remark')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when this menu item was last updated.', verbose_name='Updated At')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu for hierarchical structure.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cmfadmin.menu', verbose_name='Parent Menu')),
            ],
            options={
                'verbose_name': 'Admin Menu',
                'verbose_name_plural': 'Admin Menus',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the navigation item.', max_length=100, verbose_name='Name')),
                ('url', models.CharField(blank=True, help_text='URL for this navigation item.', max_length=255, null=True, verbose_name='URL')),
                ('icon', models.CharField(blank=True, help_text='Icon class for this navigation item.', max_length=100, null=True, verbose_name='Icon Class')),
                ('target', models.CharField(choices=[('_self', 'Self Window'), ('_blank', 'Blank Window')], default='_self', help_text='Target behavior when opening the link.', max_length=10, verbose_name='Target')),
                ('sort_order', models.IntegerField(default=10000, help_text='Order for navigation item sorting.', verbose_name='Sort Order')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this item is visible.', verbose_name='Is Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when this navigation item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when this navigation item was last updated.', verbose_name='Updated At')),
                ('nav', models.ForeignKey(help_text='Navigation container.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cmfadmin.nav', verbose_name='Navigation')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent item for hierarchical structure.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cmfadmin.navitem', verbose_name='Parent Item')),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Saved file name including extension.', max_length=255, verbose_name='Filename')),
                ('original_name', models.CharField(help_text='Original file name before upload.', max_length=255, verbose_name='Original Name')),
                ('path', models.CharField(help_text='Relative path to the saved file.', max_length=500, verbose_name='Path')),
                ('mime_type', models.CharField(choices=[('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/gif', 'GIF'), ('image/webp', 'WEBP'), ('image/bmp', 'BMP'), ('image/svg+xml', 'SVG'), ('image/avif', 'AVIF'), ('audio/mpeg', 'MP3'), ('audio/wav', 'WAV'), ('audio/ogg', 'OGG'), ('audio/flac', 'FLAC'), ('audio/aac', 'AAC'), ('audio/opus', 'OPUS'), ('video/mp4', 'MP4'), ('video/webm', 'WEBM'), ('video/x-msvideo', 'AVI'), ('video/quicktime', 'MOV'), ('video/x-matroska', 'MKV'), ('video/ogg', 'OGV'), ('application/pdf', 'PDF'), ('application/msword', 'DOC'), ('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'DOCX'), ('application/vnd.ms-excel', 'XLS'), ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'XLSX'), ('application/vnd.ms-powerpoint', 'PPT'), ('application/vnd.openxmlformats-officedocument.presentationml.presentation', 'PPTX'), ('text/plain', 'TXT'), ('application/zip', 'ZIP'), ('application/vnd.rar', 'RAR'), ('application/x-7z-compressed', '7Z'), ('application/x-tar', 'TAR'), ('application/gzip', 'GZ')], help_text='MIME type of the uploaded file.', max_length=100, verbose_name='MIME Type')),
                ('size', models.BigIntegerField(help_text='File size in bytes.', verbose_name='Size')),
                ('hash', models.CharField(db_index=True, help_text='SHA-256 hash of the file content.', max_length=64, unique=True, verbose_name='Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Upload timestamp.', verbose_name='Created At')),
                ('uploader', models.ForeignKey(blank=True, help_text='The user who uploaded the file (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Uploader')),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
            },
        ),
    ]
