# Generated by Django 6.0.1 on 2026-01-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externallink',
            name='image_url',
        ),
    ]
