# Generated by Django 6.0.2 on 2026-03-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0002_remove_externallink_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuPermission',
        ),
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
                'proxy': True,
                'default_permissions': ('view', 'change'),
                'indexes': [],
                'constraints': [],
            },
            bases=('cmfadmin.config',),
        ),
        migrations.CreateModel(
            name='EmailTemplateConfig',
            fields=[
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Template',
                'proxy': True,
                'default_permissions': ('view', 'change'),
                'indexes': [],
                'constraints': [],
            },
            bases=('cmfadmin.config',),
        ),
        migrations.CreateModel(
            name='FileConfig',
            fields=[
            ],
            options={
                'verbose_name': 'File Management',
                'verbose_name_plural': 'File Management',
                'proxy': True,
                'default_permissions': ('view', 'change'),
                'indexes': [],
                'constraints': [],
            },
            bases=('cmfadmin.config',),
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
                'proxy': True,
                'default_permissions': ('view', 'change'),
                'indexes': [],
                'constraints': [],
            },
            bases=('cmfadmin.config',),
        ),
        migrations.CreateModel(
            name='UploadConfig',
            fields=[
            ],
            options={
                'verbose_name': 'Upload Settings',
                'verbose_name_plural': 'Upload Settings',
                'proxy': True,
                'default_permissions': ('view', 'change'),
                'indexes': [],
                'constraints': [],
            },
            bases=('cmfadmin.config',),
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'default_permissions': (), 'verbose_name': 'Configuration Item', 'verbose_name_plural': 'Configuration Items'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='visible',
        ),
        migrations.AlterField(
            model_name='config',
            name='category',
            field=models.CharField(choices=[('site', 'Site Information'), ('email', 'Email Settings'), ('email_template', 'Email Template'), ('upload', 'Upload Settings'), ('file', 'File Management'), ('icons', 'Icons Management'), ('template', 'Template Management'), ('system', 'System Settings'), ('log', 'Log Management'), ('nav', 'Navigation Management'), ('links', 'External Links')], db_comment='Configuration category.', max_length=32, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='config',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(db_comment='Unique configuration key.', max_length=64, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='config',
            name='remark',
            field=models.CharField(blank=True, db_comment='Additional notes about this configuration item.', max_length=255, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='config',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.TextField(db_comment='Configuration value.', verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='sort_order',
            field=models.PositiveIntegerField(default=10000, help_text='Determines the display order of the link.', verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Icon class for this navigation item.', max_length=100, verbose_name='Icon Class'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=10000, help_text='Order for navigation item sorting.', verbose_name='Sort Order'),
        ),
    ]
