# Generated by Django 6.0.2 on 2026-03-10 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0003_delete_menupermission_emailconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplateConfig',
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'default_permissions': (), 'verbose_name': 'configuration item', 'verbose_name_plural': 'configuration items'},
        ),
        migrations.AlterModelOptions(
            name='emailconfig',
            options={'default_permissions': ('view', 'change'), 'verbose_name': 'email settings', 'verbose_name_plural': 'email settings'},
        ),
        migrations.AlterModelOptions(
            name='externallink',
            options={'ordering': ['sort_order'], 'verbose_name': 'external link', 'verbose_name_plural': 'external links'},
        ),
        migrations.AlterModelOptions(
            name='fileconfig',
            options={'default_permissions': ('view', 'change'), 'verbose_name': 'file management', 'verbose_name_plural': 'file management'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['sort_order'], 'verbose_name': 'admin menu', 'verbose_name_plural': 'admin menus'},
        ),
        migrations.AlterModelOptions(
            name='nav',
            options={'ordering': ['id'], 'verbose_name': 'navigation', 'verbose_name_plural': 'navigations'},
        ),
        migrations.AlterModelOptions(
            name='navitem',
            options={'ordering': ['sort_order'], 'verbose_name': 'navigation item', 'verbose_name_plural': 'navigation items'},
        ),
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'default_permissions': ('view', 'change'), 'verbose_name': 'site configuration', 'verbose_name_plural': 'site configuration'},
        ),
        migrations.AlterModelOptions(
            name='uploadconfig',
            options={'default_permissions': ('view', 'change'), 'verbose_name': 'upload settings', 'verbose_name_plural': 'upload settings'},
        ),
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'verbose_name': 'uploaded file', 'verbose_name_plural': 'uploaded files'},
        ),
        migrations.AddField(
            model_name='menu',
            name='permissions',
            field=models.CharField(blank=True, db_comment='Permissions associated with this menu item.', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='config',
            name='category',
            field=models.CharField(choices=[('site', 'Site Information'), ('email', 'Email Settings'), ('upload', 'Upload Settings'), ('file', 'File Management'), ('icons', 'Icons Management'), ('template', 'Template Management'), ('system', 'System Settings'), ('log', 'Log Management'), ('nav', 'Navigation Management'), ('links', 'External Links')], db_comment='Configuration category.', max_length=32, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='config',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(db_comment='Unique configuration key.', max_length=64, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='config',
            name='remark',
            field=models.CharField(blank=True, db_comment='Additional notes about this configuration item.', max_length=255, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='config',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.TextField(db_comment='Configuration value.', verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='image',
            field=models.ImageField(blank=True, help_text='The image associated with the external link.', null=True, upload_to='links/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='sort_order',
            field=models.PositiveIntegerField(default=10000, help_text='Determines the display order of the link.', verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='status',
            field=models.BooleanField(default=True, help_text='Indicates whether this link is active.', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='title',
            field=models.CharField(help_text='The title for the external link.', max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='url',
            field=models.URLField(blank=True, help_text='The URL for the external link.', verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='app_label',
            field=models.CharField(blank=True, db_comment='Application label associated with this menu item.', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, db_comment='Icon class for the menu item.', default='', max_length=50, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_key',
            field=models.CharField(db_comment='Stable hash used to uniquely identify this menu item, based on URL and parent id.', db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, db_comment='Parent menu for hierarchical structure.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cmfadmin.menu', verbose_name='parent menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='remark',
            field=models.CharField(blank=True, db_comment='Additional notes or comments about this menu item.', default='', max_length=200, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sort_order',
            field=models.PositiveIntegerField(db_comment='Order for menu sorting.', default=10000, verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(db_comment='Menu title displayed in the admin.', max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, db_comment='URL or named route for the menu item.', default='', max_length=200, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when this navigation was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this navigation is active.', verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='slug',
            field=models.SlugField(help_text='A short unique identifier used in URLs and templates. Only letters, numbers, hyphens, and underscores are allowed.', max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='title',
            field=models.CharField(help_text='The title for the navigation.', max_length=100, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Time when this navigation was last updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when this navigation item was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Icon class for this navigation item.', max_length=100, verbose_name='icon class'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Whether this item is visible.', verbose_name='is visible'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='name',
            field=models.CharField(help_text='Name of the navigation item.', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='nav',
            field=models.ForeignKey(help_text='Navigation container.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cmfadmin.nav', verbose_name='navigation'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent item for hierarchical structure.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cmfadmin.navitem', verbose_name='parent item'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=10000, help_text='Order for navigation item sorting.', verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='target',
            field=models.CharField(choices=[('_self', 'Self Window'), ('_blank', 'Blank Window')], default='_self', help_text='Target behavior when opening the link.', max_length=10, verbose_name='target'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Time when this navigation item was last updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='url',
            field=models.CharField(blank=True, help_text='URL for this navigation item.', max_length=255, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Upload timestamp.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='filename',
            field=models.CharField(help_text='Saved file name including extension.', max_length=255, verbose_name='filename'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='hash',
            field=models.CharField(db_index=True, help_text='SHA-256 hash of the file content.', max_length=64, unique=True, verbose_name='hash'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='mime_type',
            field=models.CharField(choices=[('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/gif', 'GIF'), ('image/webp', 'WEBP'), ('image/bmp', 'BMP'), ('image/svg+xml', 'SVG'), ('image/avif', 'AVIF'), ('audio/mpeg', 'MP3'), ('audio/wav', 'WAV'), ('audio/ogg', 'OGG'), ('audio/flac', 'FLAC'), ('audio/aac', 'AAC'), ('audio/opus', 'OPUS'), ('video/mp4', 'MP4'), ('video/webm', 'WEBM'), ('video/x-msvideo', 'AVI'), ('video/quicktime', 'MOV'), ('video/x-matroska', 'MKV'), ('video/ogg', 'OGV'), ('application/pdf', 'PDF'), ('application/msword', 'DOC'), ('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'DOCX'), ('application/vnd.ms-excel', 'XLS'), ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'XLSX'), ('application/vnd.ms-powerpoint', 'PPT'), ('application/vnd.openxmlformats-officedocument.presentationml.presentation', 'PPTX'), ('text/plain', 'TXT'), ('application/zip', 'ZIP'), ('application/vnd.rar', 'RAR'), ('application/x-7z-compressed', '7Z'), ('application/x-tar', 'TAR'), ('application/gzip', 'GZ')], help_text='MIME type of the uploaded file.', max_length=100, verbose_name='mime type'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='original_name',
            field=models.CharField(help_text='Original file name before upload.', max_length=255, verbose_name='original name'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='path',
            field=models.CharField(help_text='Relative path to the saved file.', max_length=500, verbose_name='path'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='size',
            field=models.BigIntegerField(help_text='File size in bytes.', verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='uploader',
            field=models.ForeignKey(blank=True, help_text='The user who uploaded the file (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='uploader'),
        ),
    ]
