# Generated by Django 6.0.2 on 2026-03-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0004_delete_emailtemplateconfig_alter_config_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='permissions',
            field=models.JSONField(blank=True, db_comment='Permissions associated with this menu item.', default='', max_length=255),
        ),
    ]
