# Generated by Django 6.0.2 on 2026-03-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0005_alter_menu_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='permissions',
            field=models.JSONField(blank=True, db_comment='Permissions associated with this menu item.', default=list, max_length=255),
        ),
    ]
