# Generated by Django 6.0.3 on 2026-03-20 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0008_remove_uploadfile_uploader_delete_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Relative path for local files, full URL for external resources.', max_length=2048, unique=True, verbose_name='URL')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='original name')),
                ('size', models.PositiveIntegerField(default=0, help_text='File size in bytes. 0 for external resources.', verbose_name='size')),
                ('hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 hex digest. Empty for external resources.', max_length=64, verbose_name='hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TestConfig',
        ),
        migrations.AlterModelOptions(
            name='emailconfig',
            options={'default_permissions': ('view', 'change'), 'verbose_name': 'Email Setting', 'verbose_name_plural': 'Email Settings'},
        ),
        migrations.AlterModelOptions(
            name='externallink',
            options={'ordering': ['sort_order'], 'verbose_name': 'External Link', 'verbose_name_plural': 'External Links'},
        ),
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'default_permissions': ('view', 'change'), 'verbose_name': 'Site Information', 'verbose_name_plural': 'Site Information'},
        ),
        migrations.AlterModelOptions(
            name='uploadconfig',
            options={'default_permissions': ('view', 'change'), 'verbose_name': 'Upload Setting', 'verbose_name_plural': 'Upload Settings'},
        ),
        migrations.AlterField(
            model_name='config',
            name='category',
            field=models.CharField(choices=[('site', 'Site Information'), ('email', 'Email Settings'), ('upload', 'Upload Settings'), ('file', 'File Management'), ('icons', 'Icons Management'), ('template', 'Template Management'), ('system', 'System Settings'), ('log', 'Log Management'), ('nav', 'Navigations'), ('links', 'External Links')], db_comment='Configuration category.', max_length=32, verbose_name='category'),
        ),
    ]
