# Generated by Django 6.0.3 on 2026-03-23 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0010_resource_file_type_resource_mime_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nav',
            options={'ordering': ['id'], 'verbose_name': 'navigation', 'verbose_name_plural': 'Navigations'},
        ),
        migrations.AlterField(
            model_name='navitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent item for hierarchical structure.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cmfadmin.navitem', verbose_name='parent nav item'),
        ),
    ]
