# Generated by Django 6.0.3 on 2026-04-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0011_alter_nav_options_alter_navitem_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nav',
            options={'ordering': ['nav_type', 'sort_order'], 'verbose_name': 'navigation item', 'verbose_name_plural': 'navigation items'},
        ),
        migrations.RemoveField(
            model_name='nav',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='nav',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='nav',
            name='title',
        ),
        migrations.AddField(
            model_name='nav',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Icon class for this navigation item.', max_length=100, verbose_name='icon class'),
        ),
        migrations.AddField(
            model_name='nav',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Whether this item is visible.', verbose_name='is visible'),
        ),
        migrations.AddField(
            model_name='nav',
            name='nav_type',
            field=models.CharField(choices=[('main', 'Main Navigation'), ('footer', 'Footer Navigation'), ('sidebar', 'Sidebar Navigation')], default='main', help_text='Which navigation group this item belongs to.', max_length=20, verbose_name='navigation type'),
        ),
        migrations.AddField(
            model_name='nav',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent item for hierarchical structure.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cmfadmin.nav', verbose_name='parent item'),
        ),
        migrations.AddField(
            model_name='nav',
            name='sort_order',
            field=models.PositiveIntegerField(default=10000, help_text='Order for sorting.', verbose_name='sort order'),
        ),
        migrations.AddField(
            model_name='nav',
            name='target',
            field=models.CharField(choices=[('_self', 'Self Window'), ('_blank', 'Blank Window')], default='_self', help_text='Target behavior when opening the link.', max_length=10, verbose_name='target'),
        ),
        migrations.AddField(
            model_name='nav',
            name='url',
            field=models.CharField(blank=True, default='', help_text='URL for this navigation item.', max_length=255, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.CreateModel(
            name='NavTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('zh-hans', '简体中文'), ('ja', '日本語'), ('ar', 'العربيّة')], max_length=10, verbose_name='language')),
                ('name', models.CharField(help_text='Display name of this navigation item.', max_length=100, verbose_name='name')),
                ('nav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cmfadmin.nav', verbose_name='navigation item')),
            ],
            options={
                'verbose_name': 'nav translation',
                'verbose_name_plural': 'nav translations',
                'ordering': ['language'],
                'unique_together': {('nav', 'language')},
            },
        ),
        migrations.DeleteModel(
            name='NavItem',
        ),
    ]
