# Generated by Django 6.0.3 on 2026-04-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0012_alter_nav_options_remove_nav_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255, unique=True, verbose_name='Alias')),
                ('target', models.CharField(max_length=255, verbose_name='Target URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'URL Alias',
                'verbose_name_plural': 'URL Aliases',
            },
        ),
        migrations.AlterModelOptions(
            name='nav',
            options={'ordering': ['nav_type', 'sort_order'], 'verbose_name': 'navigation', 'verbose_name_plural': 'navigations'},
        ),
        migrations.AlterField(
            model_name='navtranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh-hans', '简体中文'), ('ja', '日本語'), ('ar', 'العربيّة')], help_text='Which language this item belongs to.', max_length=10, verbose_name='language'),
        ),
    ]
