# Generated by Django 6.0.3 on 2026-04-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0014_theme_alter_urlalias_alias_alter_urlalias_target_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themetemplate',
            options={'ordering': ['sort_order'], 'verbose_name': 'theme template', 'verbose_name_plural': 'theme templates'},
        ),
        migrations.RemoveField(
            model_name='themetemplate',
            name='order',
        ),
        migrations.AddField(
            model_name='theme',
            name='vars',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='themetemplate',
            name='sort_order',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='themetemplate',
            name='vars',
            field=models.JSONField(default=dict),
        ),
    ]
