# Generated by Django 6.0.3 on 2026-04-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0017_alter_nav_options_remove_nav_nav_type_nav_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='image')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='link')),
                ('group', models.CharField(max_length=100, verbose_name='group')),
                ('sort_order', models.IntegerField(default=10000, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'sliders',
                'ordering': ['group', 'sort_order'],
            },
        ),
    ]
