# Generated by Django 6.0.3 on 2026-05-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0018_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externallink',
            options={'ordering': ['sort_order'], 'verbose_name': 'Partner Link', 'verbose_name_plural': 'Partner Links'},
        ),
        migrations.AddField(
            model_name='slider',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='subtitle'),
        ),
    ]
