# Generated by Django 6.0.3 on 2026-05-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmfadmin', '0019_alter_externallink_options_slider_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, upload_to='slider/', verbose_name='image'),
        ),
    ]
